# Generated by Django 5.1 on 2026-03-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Итоговый балл')),
                ('file_url', models.CharField(blank=True, max_length=500, verbose_name='PDF (URL)')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'db_table': 'certificates',
            },
        ),
    ]
