# Generated by Django 5.1 on 2026-03-15 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAnalytics',
            fields=[
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='analytics', serialize=False, to='courses.course')),
                ('total_enrolled', models.PositiveIntegerField(default=0, verbose_name='Всего зачислено')),
                ('total_completed', models.PositiveIntegerField(default=0, verbose_name='Всего завершили')),
                ('avg_test_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ср. балл тестов')),
                ('avg_sim_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ср. балл симуляций')),
                ('avg_completion_days', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Ср. дней до завершения')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Аналитика курса',
                'db_table': 'course_analytics',
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='courses.enrollment'),
        ),
    ]
