# Generated by Django 5.1 on 2026-06-07 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
        ('courses', '0004_studentgroup_enrollment_group_studentgroupmember_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Рег. номер'),
        ),
        migrations.CreateModel(
            name='DiplomaRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО (подтверждённое)')),
                ('email', models.EmailField(max_length=150, verbose_name='Email (подтверждённый)')),
                ('status', models.CharField(choices=[('pending', 'Новая'), ('issued', 'Оформлен'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='Статус')),
                ('number', models.CharField(blank=True, max_length=40, verbose_name='Рег. номер диплома')),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Итоговый балл')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='Комментарий')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diploma_request', to='courses.enrollment')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_diplomas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка на диплом',
                'verbose_name_plural': 'Заявки на дипломы',
                'db_table': 'diploma_requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
