# Generated by Django 5.1 on 2026-06-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_year',
            field=models.CharField(blank=True, max_length=4, verbose_name='Год рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport',
            field=models.CharField(blank=True, max_length=60, verbose_name='Паспортные данные'),
        ),
        migrations.AddField(
            model_name='user',
            name='reg_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Адрес прописки'),
        ),
        migrations.AddField(
            model_name='user',
            name='snils',
            field=models.CharField(blank=True, max_length=20, verbose_name='СНИЛС'),
        ),
    ]
