# Generated by Django 5.1 on 2026-03-15 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementLibrary',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('category', models.CharField(help_text='controls | indicators | pipes | valves | sensors', max_length=50, verbose_name='Категория')),
                ('type', models.CharField(max_length=50, verbose_name='Тип элемента')),
                ('icon', models.CharField(blank=True, max_length=500, verbose_name='Иконка (SVG/URL)')),
                ('default_properties', models.JSONField(default=dict, verbose_name='Свойства по умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Элемент библиотеки',
                'verbose_name_plural': 'Библиотека элементов',
                'db_table': 'element_library',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SimulationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('canvas_w', models.PositiveIntegerField(default=1200, verbose_name='Ширина холста (px)')),
                ('canvas_h', models.PositiveIntegerField(default=700, verbose_name='Высота холста (px)')),
                ('elements', models.JSONField(verbose_name='Элементы холста')),
                ('rules', models.JSONField(blank=True, default=list, verbose_name='Правила (триггеры)')),
                ('reference_scenario', models.JSONField(blank=True, default=list, verbose_name='Эталонный сценарий')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Шаблон симуляции',
                'verbose_name_plural': 'Шаблоны симуляций',
                'db_table': 'simulation_templates',
            },
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_num', models.PositiveSmallIntegerField(default=1, verbose_name='Номер попытки')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Балл')),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Макс. балл')),
                ('actions_log', models.JSONField(verbose_name='Лог действий')),
                ('deviations', models.JSONField(blank=True, default=list, verbose_name='Отклонения от эталона')),
                ('time_spent_sec', models.PositiveIntegerField(blank=True, null=True, verbose_name='Время (сек)')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_results', to='courses.enrollment')),
            ],
            options={
                'verbose_name': 'Результат симуляции',
                'verbose_name_plural': 'Результаты симуляций',
                'db_table': 'simulation_results',
            },
        ),
    ]
