# Generated by Django 5.1 on 2026-03-15 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('simulations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationtemplate',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='simulation_templates', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='simulationtemplate',
            name='module',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulation_template', to='courses.coursemodule', verbose_name='Модуль курса'),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='simulations.simulationtemplate'),
        ),
        migrations.AddIndex(
            model_name='simulationtemplate',
            index=models.Index(fields=['author'], name='simulation__author__670502_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationtemplate',
            index=models.Index(fields=['module'], name='simulation__module__061b07_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationresult',
            index=models.Index(fields=['simulation', 'enrollment'], name='simulation__simulat_f27551_idx'),
        ),
    ]
