# Generated by Django 5.1 on 2026-05-12 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('simulations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationresult',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulation_results', to='courses.enrollment'),
        ),
    ]
