# Generated by Django 5.1 on 2026-05-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0003_alter_simulationresult_enrollment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elementlibrary',
            options={'ordering': ['library_set', 'category', 'name'], 'verbose_name': 'Элемент библиотеки', 'verbose_name_plural': 'Библиотека элементов'},
        ),
        migrations.AddField(
            model_name='elementlibrary',
            name='library_set',
            field=models.CharField(choices=[('universal', 'Универсальная'), ('boiler', 'Котельная установка'), ('pump_station', 'Насосная станция'), ('substation', 'Электроподстанция')], default='universal', max_length=50, verbose_name='Библиотека АСУ'),
        ),
    ]
