# Generated by Django 5.1 on 2026-06-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0006_simulationresult_safety'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationtemplate',
            name='connections',
            field=models.JSONField(blank=True, default=list, verbose_name='Связи между элементами'),
        ),
    ]
