# Generated by Django 5.1 on 2026-03-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('archived', 'Архив')], default='draft', max_length=20, verbose_name='Статус')),
                ('level', models.PositiveSmallIntegerField(default=1, verbose_name='Уровень сложности')),
                ('cover_image', models.CharField(blank=True, max_length=500, verbose_name='Обложка (URL)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'db_table': 'courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('type', models.CharField(choices=[('lecture', 'Лекция'), ('video', 'Видео'), ('document', 'Документ'), ('test', 'Тест'), ('simulation', 'Симуляция')], max_length=20, verbose_name='Тип')),
                ('content', models.TextField(blank=True, verbose_name='Контент (HTML/Markdown)')),
                ('file_url', models.CharField(blank=True, max_length=500, verbose_name='Файл (URL)')),
                ('order_num', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязателен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Модуль курса',
                'verbose_name_plural': 'Модули курса',
                'db_table': 'course_modules',
                'ordering': ['order_num'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('completed', 'Завершено'), ('dropped', 'Отчислен')], default='active', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок сдачи')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Зачисление',
                'verbose_name_plural': 'Зачисления',
                'db_table': 'enrollments',
            },
        ),
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Не начат'), ('in_progress', 'В процессе'), ('completed', 'Завершён')], default='not_started', max_length=20)),
                ('time_spent_sec', models.PositiveIntegerField(default=0, verbose_name='Время (сек)')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Прогресс по модулю',
                'db_table': 'module_progress',
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('type', models.CharField(choices=[('single', 'Одиночный выбор'), ('multiple', 'Множественный выбор'), ('text', 'Ввод текста'), ('match', 'Сопоставление')], default='single', max_length=20)),
                ('options', models.JSONField(blank=True, default=list, verbose_name='Варианты ответа')),
                ('correct_answer', models.JSONField(verbose_name='Правильный ответ')),
                ('points', models.PositiveSmallIntegerField(default=1, verbose_name='Баллы')),
                ('order_num', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Вопрос теста',
                'verbose_name_plural': 'Вопросы теста',
                'db_table': 'test_questions',
                'ordering': ['order_num'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_num', models.PositiveSmallIntegerField(default=1, verbose_name='Номер попытки')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Балл')),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Макс. балл')),
                ('answers', models.JSONField(default=list, verbose_name='Ответы')),
                ('time_spent_sec', models.PositiveIntegerField(blank=True, null=True, verbose_name='Время (сек)')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Результат теста',
                'db_table': 'test_results',
            },
        ),
    ]
