# Generated by Django 5.1 on 2026-03-15 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Инструктор'),
        ),
        migrations.CreateModel(
            name='TestSettings',
            fields=[
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='test_settings', serialize=False, to='courses.coursemodule')),
                ('time_limit_sec', models.PositiveIntegerField(blank=True, null=True, verbose_name='Лимит времени (сек)')),
                ('max_attempts', models.PositiveSmallIntegerField(default=3, verbose_name='Макс. попыток')),
                ('passing_score', models.DecimalField(decimal_places=2, default=60, max_digits=5, verbose_name='Проходной балл (%)')),
                ('shuffle_questions', models.BooleanField(default=False, verbose_name='Перемешивать вопросы')),
                ('show_answers_after', models.BooleanField(default=True, verbose_name='Показывать ответы после')),
            ],
            options={
                'verbose_name': 'Настройки теста',
                'db_table': 'test_settings',
            },
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course'),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='unlock_after',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks', to='courses.coursemodule', verbose_name='Доступен после модуля'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='enrolled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moduleprogress',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progresses', to='courses.enrollment'),
        ),
        migrations.AddField(
            model_name='moduleprogress',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursemodule'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.coursemodule'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='courses.coursemodule'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status'], name='courses_status_67f368_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['instructor'], name='courses_instruc_77fba4_idx'),
        ),
        migrations.AddIndex(
            model_name='coursemodule',
            index=models.Index(fields=['course', 'order_num'], name='course_modu_course__916b4e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('course', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='moduleprogress',
            unique_together={('enrollment', 'module')},
        ),
        migrations.AddIndex(
            model_name='testquestion',
            index=models.Index(fields=['module'], name='test_questi_module__958611_idx'),
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['user', 'module'], name='test_result_user_id_7c88bc_idx'),
        ),
    ]
