# Generated by Django 5.1 on 2026-06-08 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_studentgroup_enrollment_group_studentgroupmember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequisite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks', to='courses.course', verbose_name='Доступен после курса'),
        ),
    ]
